server:
  port: 8082
spring:
  application:
    name: order-service
  main:
    allow-circular-references: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true